from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from config import APP_CONFIG
from utils import format_currency
import os


def generate_bill(customer_name, order_items, gst_amount, final_total):
    """Generate a professional PDF bill."""
    # Create bills directory if it doesn't exist
    if not os.path.exists("bills"):
        os.makedirs("bills")

    file_path = f"bills/bill_{customer_name.replace(' ', '_')}_{final_total}.pdf"
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        spaceAfter=30,
        alignment=1,  # Center alignment
        textColor=colors.darkgreen,
    )

    header_style = ParagraphStyle(
        "CustomHeader",
        parent=styles["Heading2"],
        fontSize=16,
        spaceAfter=20,
        textColor=colors.darkblue,
    )

    normal_style = styles["Normal"]

    story = []

    # Title
    story.append(Paragraph(APP_CONFIG["name"], title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Professional Coffee Billing System", normal_style))
    story.append(Spacer(1, 20))

    # Bill header
    story.append(Paragraph("BILL RECEIPT", header_style))
    story.append(Spacer(1, 12))

    # Customer details
    story.append(Paragraph(f"<b>Customer Name:</b> {customer_name}", normal_style))
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            f"<b>Date:</b> {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            normal_style,
        )
    )
    story.append(Spacer(1, 20))

    # Order items table
    table_data = [["Item", "Size", "Qty", "Unit Price", "Total"]]

    for item in order_items:
        table_data.append(
            [
                item["item_name"],
                item["size"],
                str(item["quantity"]),
                format_currency(item["unit_price"]),
                format_currency(item["total_price"]),
            ]
        )

    # Table styling
    table = Table(
        table_data, colWidths=[2 * inch, 1 * inch, 0.8 * inch, 1.2 * inch, 1.2 * inch]
    )
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 12),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 1), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 20))

    # Totals
    subtotal = final_total - gst_amount

    story.append(
        Paragraph(f"<b>Subtotal:</b> {format_currency(subtotal)}", normal_style)
    )
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            f"<b>GST ({APP_CONFIG['gst_rate']*100}%):</b> {format_currency(gst_amount)}",
            normal_style,
        )
    )
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            f"<b>Grand Total:</b> {format_currency(final_total)}", styles["Heading2"]
        )
    )
    story.append(Spacer(1, 20))

    # Footer
    story.append(Paragraph("Thank you for your business!", normal_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Visit us again soon!", normal_style))
    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            f"Generated by {APP_CONFIG['name']} v{APP_CONFIG['version']}",
            styles["Italic"],
        )
    )

    # Generate PDF
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    doc.build(story)

    return file_path
